window.DEVKI_PRICE_CATALOG=[
  {
    "id": "steel-d8",
    "name": "Devki D8 Deformed Bar",
    "spec": "8mm reinforcement bar • 12m length",
    "category": "steel",
    "categoryLabel": "Steel Rebar",
    "unit": "bar",
    "unitLabel": "Per Bar (12m)",
    "price": 450,
    "moq": "1 bar"
  },
  {
    "id": "steel-d10",
    "name": "Devki D10 Deformed Bar",
    "spec": "10mm reinforcement bar • 12m length",
    "category": "steel",
    "categoryLabel": "Steel Rebar",
    "unit": "bar",
    "unitLabel": "Per Bar (12m)",
    "price": 750,
    "moq": "1 bar"
  },
  {
    "id": "steel-d12",
    "name": "Devki D12 Deformed Bar",
    "spec": "12mm reinforcement bar • 12m length",
    "category": "steel",
    "categoryLabel": "Steel Rebar",
    "unit": "bar",
    "unitLabel": "Per Bar (12m)",
    "price": 1020,
    "moq": "1 bar"
  },
  {
    "id": "steel-d16",
    "name": "Devki D16 Deformed Bar",
    "spec": "16mm reinforcement bar • 12m length",
    "category": "steel",
    "categoryLabel": "Steel Rebar",
    "unit": "bar",
    "unitLabel": "Per Bar (12m)",
    "price": 2050,
    "moq": "1 bar"
  },
  {
    "id": "steel-d25",
    "name": "Devki D25 Deformed Bar",
    "spec": "25mm reinforcement bar • 12m length",
    "category": "steel",
    "categoryLabel": "Steel Rebar",
    "unit": "bar",
    "unitLabel": "Per Bar (12m)",
    "price": 4900,
    "moq": "1 bar"
  },
  {
    "id": "binding-wire",
    "name": "Binding Wire",
    "spec": "Confirm coil or pack weight before ordering",
    "category": "steel",
    "categoryLabel": "Steel Accessories",
    "unit": "unit",
    "unitLabel": "Per Unit",
    "price": 2780,
    "moq": "1 unit"
  },
  {
    "id": "hoop-iron",
    "name": "Hoop Iron",
    "spec": "Confirm width, gauge and coil length",
    "category": "steel",
    "categoryLabel": "Steel Accessories",
    "unit": "unit",
    "unitLabel": "Per Unit",
    "price": 3000,
    "moq": "1 unit"
  },
  {
    "id": "round-r6",
    "name": "R6 Round Bar",
    "spec": "6mm plain round bar • confirm length",
    "category": "steel",
    "categoryLabel": "Round Bar",
    "unit": "bar",
    "unitLabel": "Per Bar",
    "price": 210,
    "moq": "1 bar"
  },
  {
    "id": "round-r8",
    "name": "R8 Round Bar",
    "spec": "8mm plain round bar • confirm length",
    "category": "steel",
    "categoryLabel": "Round Bar",
    "unit": "bar",
    "unitLabel": "Per Bar",
    "price": 450,
    "moq": "1 bar"
  },
  {
    "id": "round-r10",
    "name": "R10 Round Bar",
    "spec": "10mm plain round bar • confirm length",
    "category": "steel",
    "categoryLabel": "Round Bar",
    "unit": "bar",
    "unitLabel": "Per Bar",
    "price": 850,
    "moq": "1 bar"
  },
  {
    "id": "round-r12",
    "name": "R12 Round Bar",
    "spec": "12mm plain round bar • confirm length",
    "category": "steel",
    "categoryLabel": "Round Bar",
    "unit": "bar",
    "unitLabel": "Per Bar",
    "price": 1350,
    "moq": "1 bar"
  },
  {
    "id": "round-r16",
    "name": "R16 Round Bar",
    "spec": "16mm plain round bar • confirm length",
    "category": "steel",
    "categoryLabel": "Round Bar",
    "unit": "bar",
    "unitLabel": "Per Bar",
    "price": 2300,
    "moq": "1 bar"
  },
  {
    "id": "shs-20",
    "name": "SHS 20mm",
    "spec": "Square hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 500,
    "moq": "1 piece"
  },
  {
    "id": "shs-25",
    "name": "SHS 25mm",
    "spec": "Square hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 950,
    "moq": "1 piece"
  },
  {
    "id": "shs-40-50",
    "name": "SHS 40–50mm",
    "spec": "Square hollow section • size-dependent listed rate",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 1950,
    "moq": "1 piece"
  },
  {
    "id": "shs-75",
    "name": "SHS 75mm",
    "spec": "Square hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 8000,
    "moq": "1 piece"
  },
  {
    "id": "shs-125-150",
    "name": "SHS 125–150mm",
    "spec": "Square hollow section • size-dependent listed rate",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 28872,
    "moq": "1 piece"
  },
  {
    "id": "rhs-40x20",
    "name": "RHS 40×20mm",
    "spec": "Rectangular hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 1100,
    "moq": "1 piece"
  },
  {
    "id": "rhs-50x25",
    "name": "RHS 50×25mm",
    "spec": "Rectangular hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 1282,
    "moq": "1 piece"
  },
  {
    "id": "rhs-75x50-100x50",
    "name": "RHS 75×50–100×50mm",
    "spec": "Rectangular hollow section • size-dependent listed rate",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 4076,
    "moq": "1 piece"
  },
  {
    "id": "rhs-150x100-200x100",
    "name": "RHS 150×100–200×100mm",
    "spec": "Rectangular hollow section • size-dependent listed rate",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 7900,
    "moq": "1 piece"
  },
  {
    "id": "chs-half-1",
    "name": "CHS ½–1 inch",
    "spec": "Circular hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 700,
    "moq": "1 piece"
  },
  {
    "id": "chs-1-5-2",
    "name": "CHS 1½–2 inch",
    "spec": "Circular hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 1200,
    "moq": "1 piece"
  },
  {
    "id": "chs-3-4",
    "name": "CHS 3–4 inch",
    "spec": "Circular hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 4961,
    "moq": "1 piece"
  },
  {
    "id": "chs-5-6",
    "name": "CHS 5–6 inch",
    "spec": "Circular hollow section • confirm wall thickness and length",
    "category": "tubes",
    "categoryLabel": "Steel Tubes",
    "unit": "piece",
    "unitLabel": "Per Piece",
    "price": 19950,
    "moq": "1 piece"
  },
  {
    "id": "simba-32",
    "name": "Simba Cement 32.5R",
    "spec": "General-purpose cement • 50kg bag",
    "category": "cement",
    "categoryLabel": "Cement",
    "unit": "bag",
    "unitLabel": "Per 50kg Bag",
    "price": 550,
    "moq": "1 bag"
  },
  {
    "id": "simba-42",
    "name": "Simba Cement 42.5N / 42.5R",
    "spec": "Higher-strength cement • confirm current grade • 50kg bag",
    "category": "cement",
    "categoryLabel": "Cement",
    "unit": "bag",
    "unitLabel": "Per 50kg Bag",
    "price": 640,
    "moq": "1 bag"
  },
  {
    "id": "rhino-32",
    "name": "Rhino Cement 32.5R",
    "spec": "General-purpose cement • 50kg bag",
    "category": "cement",
    "categoryLabel": "Cement",
    "unit": "bag",
    "unitLabel": "Per 50kg Bag",
    "price": 510,
    "moq": "1 bag"
  },
  {
    "id": "rhino-42",
    "name": "Rhino Cement 42.5N",
    "spec": "Higher-strength cement • 50kg bag",
    "category": "cement",
    "categoryLabel": "Cement",
    "unit": "bag",
    "unitLabel": "Per 50kg Bag",
    "price": 600,
    "moq": "1 bag"
  },
  {
    "id": "mavuno-planting-50",
    "name": "Mavuno Planting Fertilizer",
    "spec": "Confirm current formulation • 50kg bag",
    "category": "fertilizer",
    "categoryLabel": "Fertilizer",
    "unit": "bag",
    "unitLabel": "Per 50kg Bag",
    "price": 2900,
    "moq": "1 bag"
  },
  {
    "id": "mavuno-topdress-50",
    "name": "Mavuno Top-Dressing Fertilizer",
    "spec": "Confirm current formulation • 50kg bag",
    "category": "fertilizer",
    "categoryLabel": "Fertilizer",
    "unit": "bag",
    "unitLabel": "Per 50kg Bag",
    "price": 2200,
    "moq": "1 bag"
  },
  {
    "id": "mavuno-25",
    "name": "Mavuno Fertilizer",
    "spec": "Confirm formulation • 25kg bag",
    "category": "fertilizer",
    "categoryLabel": "Fertilizer",
    "unit": "bag",
    "unitLabel": "Per 25kg Bag",
    "price": 1450,
    "moq": "1 bag"
  },
  {
    "id": "industrial-packaging",
    "name": "Industrial Packaging",
    "spec": "Confirm bag construction, print and order quantity",
    "category": "packaging",
    "categoryLabel": "Packaging",
    "unit": "unit",
    "unitLabel": "Per Unit",
    "price": 50,
    "moq": "Confirm MOQ"
  }
];
